version: '3'

services:
  softether:
    container_name: con_softether
    image: phamphu232/softethervpn:5.02.5180
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      # - 53:53
      - 444:443
      - 992:992
      - 1194:1194/udp
      - 5555:5555
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/udp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./volumes/mnt:/mnt"
      - "./volumes/chain_certs:/usr/local/bin/chain_certs"
      - "./volumes/server_log:/usr/local/bin/server_log"
      - "./volumes/security_log:/usr/local/bin/security_log"
      - "./volumes/packet_log:/usr/local/bin/packet_log"
